### ISSUE TITLE
Ajustar posición el juego y el banner

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#24]
Funciona en dispositivos de tamaño distinto (escalado/centrado) ✖️ (problema con el banner en ciertos dispositivos)
Hay en dispositivos que no se puede jugar, debido a que el banner se superpone a los códigos de colores. El AdView debería estar debajo del SurfaceView jugando con los contraints y no por encima. Si queremos que el AdView aparezca encima, no podemos tenerlo en las escenas de nivel y solo podría verse en el menú.

![image](https://github.com/javics2002/VDM/assets/49459590/683f0646-2b5c-4fcb-b888-c2a000aa9cd9)

![image](https://github.com/javics2002/VDM/assets/49459590/fc6b64d7-f263-4172-9f2d-e56a79750f1e)

**Comment by druiz07** [comment]
Ahora el banner solo esta visible en el menú principal, haciendo así que en cualquier dispositivo se juegue con normalidad
A parte el banner se ha hecho mas pequeño
