### ISSUE TITLE
No romper la arquitectura motor-juego

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#29]
Rompéis la arquitectura, hacéis que la parte de motor conozca cosas que son de la lógica (por ejemplo AndroidEngine::loadGameData, AndroidEngine::saveData o  en el onAdDismissedFullScreenContent de AndroidRewardedAd::tryLoadAd())

**Comment by druiz07** [comment]
Por la parte del anuncio ahora cualquier escena recibe el mensaje de Anuncio y cada una se encarga de gestionarlo, aunque en nuestro caso solo lo gestiona(hace algo el metodo) la escena GameOver , puesto que el resto de clases no activan anuncio

**Comment by javics2002** [comment]
Si no se asigna @josemiguelvdz lo haré yo cuando termine

**Comment by josemiguelvdz** [comment]
Los métodos SaveData() y LoadData() rompen con la separación de lógica-motor porque contienen información sobre las clases de lógica (Serializables). Si se moviesen al apartado de lógica, no se rompería ningún tipo de separación. El problema es que, si se mueven a lógica, no se pueden utilizar las funciones de android para abrir archivos, escribir y leer en ellos. Por ello, se mantendrá la misma estructura.

**Comment by josemiguelvdz** [comment]
Se ha arreglado la ruptura de la arquitectura del guardado.
Ahora, el motor solo se encarga de abrir el fichero y ahora es la LÓGICA del juego quién se encarga de realizar el guardado/carga de datos. 

Se han comentado las nuevas funciones del motor.
![image](https://github.com/javics2002/VDM/assets/75903737/0890a696-7443-4849-a6d9-11a3d83e1958)
