### ISSUE TITLE
Trasladar arreglos de la práctica 1

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#30]
Seguís con problemas que se indicaron ya en práctica anterior, como mantener GameObject en Engine, no usar synchronized ni volatile, transformar coordenadas de input en la lógica.

**Comment by javics2002** [comment]
@josemiguelvdz debes volver a poner las transiciones entre escenas

**Comment by josemiguelvdz** [comment]
Se han implementado las transiciones.
