### ISSUE TITLE
Load y Save seguidos en onCreate

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#31]
Por qué tenéis en el onCreate() estas dos líneas seguidas:

// Sobreescribir datos de guardado

_engineAndroid.loadGameData();

_engineAndroid.saveGameData();

**Comment by josemiguelvdz** [comment]
Se ha eliminado la línea que guardaba los datos. Solo se necesita la primera línea, responsable de la carga de los datos, ya que el guardado se realiza en distintas partes del código.
