### ISSUE TITLE
Fichas default al conseguir más intentos

### ISSUE THREAD

**Issue by javics2002** [javics2002/VDM#33]
En modo rápido, al conseguir 2 intentos más, los intentos anteriores aparecen con la apariencia original:

![image](https://github.com/javics2002/VDM/assets/49459590/35efe012-4dff-4d5a-bc3e-026b41b0a6fc)

**Comment by druiz07** [comment]
Tras todo el cambio de funcionamiento en las combinaciones y los colores ahora no hay ningún problema con +2 intentos ni en modo rápido ni en explorar mundos , tras haber comprado varias skins y haber perdido y jugado varias veces de seguido a distintos modos , no se aprecia ningún fallo en las fichas
